### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by AlexisTM** [1n9i9c7om/CATSBot#17]
Hey there, 

There is a typo on the `butto_watch` file.

https://github.com/1n9i9c7om/CATSBot/tree/master/CATSBot/Resources/720p/chest

**Comment by p410n3** [comment]
Thanks we willl get that fixed today.

**Comment by ahmet0909** [comment]
is this program works by knowing the pictures?

**Comment by AlexisTM** [comment]
@ahmet0909 Yes it does => look on the image for known pictures

**Comment by ahmet0909** [comment]
thank you it is not counting defeat and win,need to be updated

**Comment by AlexisTM** [comment]
Outdated.
